[tasks.build-window-openssl]
script = '''
docker run --rm -it -v %cd%:/root/project -v /opt/cargo/registry:/usr/local/cargo/registry -v /opt/cargo/git:/usr/local/cargo/git openssl1-0-2u:1.65.0 cargo run --bin openssl-connector
'''
[tasks.build-window-ntex-tls]
script = '''
docker run --rm -it -v %cd%:/root/project -v /opt/cargo/registry:/usr/local/cargo/registry -v /opt/cargo/git:/usr/local/cargo/git openssl1-0-2u:1.65.0 cargo run --bin ntex-connector
'''
